# Generated by Django 4.2.5 on 2023-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedUserBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('bid_amount', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('bid_msg', models.TextField()),
            ],
        ),
    ]
